name: 'ci'
on:
  - push
  - pull_request
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: 'Install pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.7
          run_install: false
      - name: 'Install dependency'
        run: pnpm install
      - name: 'Run unit tests'
        run: pnpm test
